---

- name: Docker group
  group:
    name: docker

- name: Rancher user
  user:
    name: rancher
    system: yes
    groups: docker

- name: SSH directory
  file:
    path: /home/rancher/.ssh
    owner: rancher
    group: rancher
    mode: '0700'
    state: directory

- name: Save authorized keys (from ansible02c:/root)
  copy:
    content: "{{ rancher_ssh_pub }}"
    owner: rancher
    group: rancher
    dest: /home/rancher/.ssh/authorized_keys
    mode: '0644'

- name: Dirs
  file:
    path: /etc/systemd/system/docker.service.d
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Open up the proxy
  template:
    src: etc/systemd/system/docker.service.d/proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/proxy.conf
    mode: '0755'

- name: Restart docker
  shell: |
    systemctl daemon-reload
    systemctl restart docker
