---

- name: Build rancher-cluster.yml
  template:
    src: root/rancher/rancher-cluster.yml.j2
    dest: /root/rancher/rancher-cluster.yml

- name: Get RKE
  get_url:
    url: https://github.com/rancher/rke/releases/download/v0.2.8/rke_linux-amd64
    dest: /usr/local/bin/rke
    mode: '0755'

- name: Run rke
  shell: |
    echo /usr/local/bin/rke up --config /root/rancher/rancher-cluster.yml
